### ISSUE TITLE
피드백과 이슈 등록 시 생기는 버그 없애기

### ISSUE THREAD

**Issue by 100Gyeon** [Neogasogaeseo/Naega-Web#184]
## Description
피드백/이슈 등록 시 완료 버튼을 빠르게 n번 누르면 같은 내용을 가진 n개의 피드백/이슈가 추가된다.

## To Reproduce
1. 완료 버튼 빠르게 여러 번 눌렀을 때 버그 생성
2. 똑같은 내용의 피드백/이슈 여러 개 추가되는 문제

## Expected behavior
완료 버튼 한 번만 누를 수 있게 수정

## Screenshots
|피드백 작성 중인 화면|피드백 2개 등록된 모습|
|-|-|
|<img src="https://user-images.githubusercontent.com/58380158/153458957-fcfc6ba6-f481-4e97-8f5c-ecc6b6aeef81.png" width="200px">|<img src="https://user-images.githubusercontent.com/58380158/153459069-8760b6ea-c0d7-4a21-a4b4-0575a11940ac.png" width="200px">|

|이슈 등록 페이지|이슈 2개 등록된 모습|
|-|-|
|<img src="https://user-images.githubusercontent.com/58380158/153374556-26895a3a-33cd-4c85-a2fc-112fad360bda.png" width="200px">|<img src="https://user-images.githubusercontent.com/58380158/153374874-283f9db0-f27a-431f-8dba-a57d5c1e40f5.png" width="200px">|

**Comment by 100Gyeon** [comment]
같은 내용으로 여러 개 등록되면 key가 중복되는 문제도 발생함

![image](https://user-images.githubusercontent.com/58380158/153465352-e4826012-9c0c-4a4d-bb0d-9369e73d1115.png)

**Comment by SeojinSeojin** [comment]
isConforming 같은 상태를 추가해서 POST요청을 보내면 isConforming을 true로 주고 버튼 안에는 disabled={isConfirming} 이런 식으로 프롭을 주면 좋을 것 같아유!!

**Comment by 100Gyeon** [comment]
좋은 방법이네유😉 참고할게 ㅎㅎ
