### ISSUE TITLE
키워드 조회 뷰 수정

### ISSUE THREAD

**Issue by SeojinSeojin** [Neogasogaeseo/Naega-Web#286]
## ✨ 어떤 기능인가요?
<img width="298" alt="image" src="https://user-images.githubusercontent.com/48249505/166871643-5e91f936-6a0b-4e3c-948a-ddfc642d3f64.png">

## ✅ To Dos

- [ ] 키워드 타입에 횟수 추가
- [ ] 디자인 바꿀 부분 바꾸기
- [ ] 서버통신 바꿀 부분 바꾸기

**Comment by 100Gyeon** [comment]
지금 pc에서 이렇게 보이고 있어서 이 부분도 같이 수정하면 좋을 것 같습니다~!
![image](https://user-images.githubusercontent.com/58380158/167285111-af4111fe-18b4-4567-9ea4-7db8defe90da.png)
