### ISSUE TITLE
이미지 업로드 자동 회전 고치기

### ISSUE THREAD

**Issue by SeojinSeojin** [Neogasogaeseo/Naega-Web#356]
## ✨ 어떤 기능인가요?
가로로 회전되는 이미지를 고칩니다
- https://w1640551438-zfb305914.slack.com/archives/C03ABKQDRUH/p1653747557263789
- https://w1640551438-zfb305914.slack.com/archives/C03ABKQDRUH/p1653571836560119

**Comment by 100Gyeon** [comment]
해결 방법은 아니지만 EXIF 관련 유용한 정보가 많은 블로그 글
: https://wooncloud.tistory.com/111
