### ISSUE TITLE
인앱 브라우저 메우기

### ISSUE THREAD

**Issue by SeojinSeojin** [Neogasogaeseo/Naega-Web#357]
## ✨ 어떤 기능인가요?
인앱 브라우저를 메운다

<img width="400" alt="image" src="https://user-images.githubusercontent.com/48249505/173184431-f7383cbc-48bf-4f2a-8a7e-9dc0fade6efc.png">

- https://w1640551438-zfb305914.slack.com/archives/C02RWNJFWGM/p1653798185183119
- https://w1640551438-zfb305914.slack.com/archives/C02RK2ERTQX/p1653828480683139

**Comment by NamJwong** [comment]
인앱 브라우저를 메워야
