### ISSUE TITLE
팀 메인에서 팀장 판별 로직에 isHost 값도 활용하도록 하기 +팀 나가기 모달에서 활용

### ISSUE THREAD

**Issue by NamJwong** [Neogasogaeseo/Naega-Web#372]
## ✨ 어떤 기능인가요?
팀 메인에서 지금은 서버에서 팀장을 0번 인덱스로 주기 때문에 0번 인덱스를 팀장이라고 처리를 해주고 있습니다

그런데 팀장 탈퇴 이슈라든지 팀장의 팀 나가기 권한 위임 오류라든지 이런 문제들을 겪으면서
이렇게 외부(서버) 요인에 많이 의존하는 코드는 좋지 않다고 느꼈습니다
즉, <팀장이 무조건 0번으로 올 것이다>라는 것은 클라 입장에서 불확실성이 있기 때문에 서버에서 보내주는 isHost라는 값을 직접 활용하는 것이 좋을 것 같습니다

그렇다고 0번 인덱스를 바로 가져다 쓰는 로직을 아예 버리면 효율이 떨어지니 기존 로직에 isHost 확인 조건을 추가해서 이중으로 확인하도록 하려고 합니다

\+) 팀 나가기 모달에서 위 isHost 값 활용하기
팀 메인에서 팀 나가기 모달로 isHost 값을 전달해주는데, 그것을 활용하지 않고 팀원 리스트의 길이가 1이면 팀장으로 판단하도록 해놨습니다.
팀장 1인팀인지를 판별할 때 쓰는 것인데, 그냥 1인팀이나 팀장 1인팀이나 똑같이 그 1인이 팀장인 것이 자명하다고 생각했기 때문입니다.

그렇지만 이것 또한 위 같은 이슈를 겪고 안전한 방법이 아니라는 것을 알게 됐고,
팀 메인에서 확실하게 판별하여 넘겨주는 isHost 값을 활용하도록 수정하려고 합니다.

\++) 팀원 관리 뷰에서 팀장/팀원 구분 해주기

## ✅ To Dos

- [ ] 팀 메인에서 팀장 판별 로직에 isHost 값도 활용하도록 하기
- [ ] 팀 나가기 모달에서도 같은 값 활용하기
- [ ] 팀원 관리 뷰에서 팀장/팀원 구분 해주기

**Comment by NamJwong** [comment]
@ozzing @hujumee 팀 메인 & 팀 나가기 팀장 확인 로직 클라 코드에서도 이렇게 더 확실하게 체크할 수 있도록 하겠습니다 ! !

**Comment by ozzing** [comment]
너무 좋아용! 👍
